# @see https://github.com/nelmio/alice/blob/master/doc/getting-started.md
nelmio_alice:
    locale: 'fr_FR'
    seed: 1
    functions_blacklist:
       - 'current'
    loading_limit: 5
    max_unique_values_retry: 150
